import './index.html';
import './index.scss';
import './js/mobileMenu';
import "./js/showAllElements";
import "./js/showBrands";
import "./js/showDevice";
import "./js/modals";
import "./js/swiper";
import "./js/swiper-slider";
